function joint_pos = exo_joint_pos(in1)
%EXO_JOINT_POS
%    JOINT_POS = EXO_JOINT_POS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    06-Mar-2023 12:39:13

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = cos(q4);
t6 = cos(q5);
t7 = sin(q1);
t8 = sin(q2);
t9 = sin(q3);
t10 = sin(q4);
t11 = sin(q5);
t12 = t2.*t3;
t13 = t2.*t8;
t14 = t3.*t7;
t15 = t7.*t8;
t22 = t2.*4.505e-1;
t23 = t7.*4.505e-1;
t16 = -t15;
t17 = t13+t14;
t18 = t12.*(2.19e+2./5.0e+2);
t19 = t13.*(2.19e+2./5.0e+2);
t20 = t14.*(2.19e+2./5.0e+2);
t21 = t15.*(2.19e+2./5.0e+2);
t24 = -t21;
t25 = t12+t16;
t26 = t4.*t17;
t27 = t9.*t17;
t38 = t19+t20+t23;
t28 = t4.*t25;
t29 = t9.*t25;
t30 = -t27;
t39 = t18+t22+t24;
t31 = t26+t29;
t32 = t28+t30;
t35 = -t5.*(t27-t28);
t36 = -t10.*(t27-t28);
t43 = t5.*(t27-t28).*(-2.19e+2./5.0e+2);
t44 = t10.*(t27-t28).*(-2.19e+2./5.0e+2);
t33 = t5.*t31;
t34 = t10.*t31;
t37 = -t34;
t40 = t33.*(2.19e+2./5.0e+2);
t41 = t34.*(2.19e+2./5.0e+2);
t45 = t33+t36;
t42 = -t41;
t46 = t35+t37;
joint_pos = reshape([0.0,0.0,t22,t23,t39,t38,t39,t38,t39+t42+t43,t38+t40+t44,t39+t42+t43-t6.*(t34+t5.*(t27-t28)).*4.505e-1-t11.*t45.*4.505e-1,t38+t40+t44-t11.*(t34+t5.*(t27-t28)).*4.505e-1+t6.*t45.*4.505e-1],[2,6]);
