function joint_pos = human_joint_pos(in1)
%HUMAN_JOINT_POS
%    JOINT_POS = HUMAN_JOINT_POS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    06-Mar-2023 12:39:13

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = cos(q4);
t6 = cos(q5);
t7 = sin(q1);
t8 = sin(q2);
t9 = sin(q3);
t10 = sin(q4);
t11 = sin(q5);
t12 = t2.*t3;
t13 = t2.*t8;
t14 = t3.*t7;
t15 = t7.*t8;
t31 = t2.*4.4835e-2;
t32 = t7.*4.4835e-2;
t16 = -t15;
t17 = t13+t14;
t33 = t12.*4.4835e-2;
t34 = t13.*4.4835e-2;
t35 = t14.*4.4835e-2;
t36 = t15.*4.4835e-2;
t18 = t12+t16;
t19 = t4.*t17;
t20 = t9.*t17;
t37 = -t36;
t45 = t32+t34+t35;
t21 = t4.*t18;
t22 = t9.*t18;
t23 = -t20;
t46 = t31+t33+t37;
t24 = t19+t22;
t25 = t21+t23;
t28 = -t5.*(t20-t21);
t29 = -t10.*(t20-t21);
t41 = t5.*(t20-t21).*(-4.4835e-2);
t42 = t10.*(t20-t21).*(-4.4835e-2);
t26 = t5.*t24;
t27 = t10.*t24;
t30 = -t27;
t38 = t26.*4.4835e-2;
t39 = t27.*4.4835e-2;
t43 = t26+t29;
t40 = -t39;
t44 = t28+t30;
joint_pos = reshape([0.0,0.0,t31,t32,t46,t45,t46,t45,t40+t41+t46,t38+t42+t45,t40+t41+t46-t6.*(t27+t5.*(t20-t21)).*4.4835e-2-t11.*t43.*4.4835e-2,t38+t42+t45-t11.*(t27+t5.*(t20-t21)).*4.4835e-2+t6.*t43.*4.4835e-2],[2,6]);
